# See https://pre-commit.ci
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: |
    [pre-commit.ci] pre-commit autoupdate
  autoupdate_schedule: weekly
  skip: []
  submodules: false
