name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0

    - name: Install package dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch

    - name: Install package
      run: |
        python -m pip install -e .

    - name: Run linting
      run: |
        python -m pip install ruff
        ruff check .
        ruff format . --check

    - name: Install test dependencies
      run: |
        python -m pip install pytest pytest-cov pytest-mock

    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=targetcli --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Check CLI help
      run: |
        targetcli --help

    - name: Build package
      run: |
        hatch build
